# Generated by Django 4.0.1 on 2022-02-18 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('tipoProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projecto.tipoproducto', verbose_name='Tipo producto')),
            ],
        ),
    ]
