# Generated by Django 4.0.1 on 2022-02-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='TipoProducto',
        ),
    ]
