# Generated by Django 4.0.1 on 2022-07-29 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0003_alter_proveedores_documento'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('Compra_Id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Compra Id')),
                ('fechaCompra', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha compra')),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha actualización')),
            ],
            options={
                'db_table': 'tblCompras',
            },
        ),
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('estadoCompra_Id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Estado compra Id')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('dateCreate', models.DateTimeField(auto_now=True, null=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tblEstadoCompra',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('detalleCompra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Detalle compra Id')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('precioCompra', models.FloatField(verbose_name='Precio compra')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compra.compra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
            ],
            options={
                'db_table': 'tblDetalleCompra',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='estadoCompra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compra.estadocompra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedores'),
        ),
    ]
