# Generated by Django 4.0.1 on 2022-07-29 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='dateUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha compra'),
        ),
    ]
