# Generated by Django 4.0.1 on 2022-07-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_alter_compra_dateupdate_alter_compra_fechacompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
