# Generated by Django 4.0.1 on 2022-07-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_detallecompra_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='Compra_Id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Compra Id'),
        ),
    ]
