# Generated by Django 4.0.1 on 2022-07-30 00:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_alter_detallecompra_detallecompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='dateUpdate',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.compra'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precioCompra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio compra'),
        ),
    ]
