# Generated by Django 4.0.1 on 2022-02-02 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'tblDepartamentos',
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'tblTipoPersona',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('DepartamentoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.tipopersona')),
            ],
            options={
                'db_table': 'tblTipoDocumento',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('DepartamentoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.departamentos')),
            ],
            options={
                'db_table': 'tblMunicipios',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('documento', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero documento')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('celular', models.IntegerField(default=0, verbose_name='Celular')),
                ('correo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Correo electronico')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('nombreContacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre contacto')),
                ('celularContacto', models.IntegerField(blank=True, default=0, null=True, verbose_name='Celular contacto')),
                ('dateCreate', models.DateTimeField(auto_now=True, null=True)),
                ('dateUpdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('departamentoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.departamentos')),
                ('municipioId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.municipios')),
                ('tipoDocumentoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.tipodocumento', verbose_name='Tipo documento')),
                ('tipoPersonaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.tipopersona', verbose_name='Tipo persona')),
            ],
            options={
                'db_table': 'tblClientes',
            },
        ),
    ]
