# Generated by Django 4.0.1 on 2022-02-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='DepartamentoId',
            new_name='TipoPersonaId',
        ),
    ]
