# Generated by Django 4.0.1 on 2022-02-07 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_departamentoid_tipodocumento_tipopersonaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.BigIntegerField(default=0, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celularContacto',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Celular contacto'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='TipoPersonaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.tipopersona', verbose_name='Tipo persona'),
        ),
    ]
