# Generated by Django 4.0.1 on 2022-02-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_clientes_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(default=0, max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celularContacto',
            field=models.CharField(blank=True, default=0, max_length=15, null=True, verbose_name='Celular contacto'),
        ),
    ]
