# Generated by Django 4.0.1 on 2022-02-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_clientes_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celularContacto',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular contacto'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='documento',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Número documento'),
        ),
    ]
