# Generated by Django 4.0.1 on 2022-02-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_paises_departamentos_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.paises', verbose_name='Paises'),
        ),
    ]
