# Generated by Django 4.0.1 on 2022-02-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_tipodocumento_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='documento',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Número documento'),
        ),
    ]
