# Generated by Django 4.0.1 on 2022-07-30 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_productos_cantidad_productos_precio_venta'),
        ('cliente', '0008_alter_clientes_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('estadoVenta_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='Estado Venta Id')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'db_table': 'tblEstadoVenta',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Venta_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='Venta Id')),
                ('fechaVenta', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha venta')),
                ('dateUpdate', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha actualización')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.clientes')),
                ('estadoVenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.estadoventa')),
            ],
            options={
                'db_table': 'tblVentas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('detalleVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='Detalle venta Id')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('precioVenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio compra')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'db_table': 'tblDetalleVenta',
            },
        ),
    ]
